command:
  - "python"
  - "-m"
  - "uvicorn"
  - "app:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8000"

env:
  - name: ENDPOINT_NAME
    value: '<SEU_ENDPOINT_LAKEBASE>'
  - name: PGHOST
    value: '<SEU_HOST_LAKEBASE>'
  - name: PGPORT
    value: '5432'
  - name: PGDATABASE
    value: '<SEU_DATABASE>'
  - name: PGUSER
    value: '<SERVICE_PRINCIPAL_ID>'
  - name: PGPASSWORD
    value: '<SUA_SENHA>'
  - name: PGSSLMODE
    value: 'require'
  - name: SERVING_ENDPOINT
    value: 'databricks-llama-4-maverick'
