command:
  - "python"
  - "-m"
  - "uvicorn"
  - "app:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8000"

env:
  - name: ENDPOINT_NAME
    value: 'projects/sentinela/branches/production/endpoints/primary'
  - name: PGHOST
    value: '***LAKEBASE_HOST***'
  - name: PGPORT
    value: '5432'
  - name: PGDATABASE
    value: 'sentinela'
  - name: PGUSER
    value: '***SERVICE_PRINCIPAL_ID***'
  - name: PGSSLMODE
    value: 'require'
