command:
  - "python"
  - "-m"
  - "uvicorn"
  - "app:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8000"

env:
  - name: PGHOST
    value: 'ep-lively-paper-d2kzljpk.database.us-east-1.cloud.databricks.com'
  - name: PGPORT
    value: '5432'
  - name: PGDATABASE
    value: 'cruds_db'
  - name: PGUSER
    value: '2fa8415e-334d-495f-8e38-9c5e61ae1752'
  - name: PGPASSWORD
    value: 'dbx-cruds-2026'
  - name: PGSSLMODE
    value: 'require'
  - name: SERVING_ENDPOINT
    value: 'databricks-llama-4-maverick'

resources:
  - name: serving-endpoint
    serving_endpoint:
      name: databricks-llama-4-maverick
      permission: CAN_QUERY
